version: '3.8'

services:
  db_finic:
    image: postgres:14
    container_name: postgres_db_finic
    env_file:
      - ../.env
    volumes:
      - postgres_data_finic:/var/lib/postgresql/data
    networks:
      - portfolio_network_finic
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis_finic:
    image: redis:6
    container_name: redis_finic
    networks:
      - portfolio_network_finic

  web_finic:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: django_web_finic
    command: sh -c "/entrypoint.sh && gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ../app:/app
      - ../app/static:/app/static
      - ../app/media:/app/media
    env_file:
      - ../.env
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
    depends_on:
      db_finic:
        condition: service_healthy
      redis_finic:
        condition: service_started
    ports:
      - "8032:8000"
    networks:
      - portfolio_network_finic

  telegram_bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: telegram_bot_finic
    command: python manage.py bot
    volumes:
      - ../app:/app
    env_file:
      - ../.env
    depends_on:
      - db_finic
      - web_finic
    networks:
      - portfolio_network_finic

networks:
  portfolio_network_finic:
    driver: bridge

volumes:
  postgres_data_finic:
