version: '3.8'

services:
  db_finic:
    image: postgres:14
    container_name: postgres_db_finic
    env_file:
      - ../.env
    ports:
      - "5436:5432"
    volumes:
      - postgres_data_finic:/var/lib/postgresql/data
    networks:
      - portfolio_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis_finic:
    image: redis:6
    container_name: redis_finic
    ports:
      - "6391:6379"
    networks:
      - portfolio_network

  web_finic:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: django_web_finic
    command: sh -c "/entrypoint.sh && python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8082"
    volumes:
      - ../app:/app
      - ../app/static:/app/static
      - ../app/media:/app/media
    env_file:
      - ../.env
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
    depends_on:
      db_finic:
        condition: service_healthy
      redis_finic:
        condition: service_started
    ports:
      - "127.0.0.1:8086:8082"
    networks:
      - portfolio_network

  telegram_bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: telegram_bot_finic
    command: python manage.py bot
    volumes:
      - ../app:/app       # исправлено
    env_file:
      - ../.env
    depends_on:
      - db_finic
      - web_finic
    networks:
      - portfolio_network

networks:
  portfolio_network:
    driver: bridge

volumes:
  postgres_data_finic:
